### ISSUE TITLE
Creating exercise with same name

### ISSUE THREAD

**Issue by miqdadamirali** [DimitreBogdanov/GymBuddy#2]
I was able to create a second exercise with the same name as the first by simple adding a space at the end.

Exercise 1: "bruh"
Exercise 2: "bruh " but read as "bruh"

<img width="387" alt="screen shot 2016-01-19 at 11 41 04 pm" src="https://cloud.githubusercontent.com/assets/9101445/12440102/22c0ce74-bf06-11e5-8f75-a4bf999cfc6e.png">

**Comment by DimitreBogdanov** [comment]
Fixed under commit 545a6cb
